### PR TITLE
karen frens

### PR DESCRIPTION
**Pull request by StarUndrscre**
adds 18 new jumpy karen frens, courtesy of subpar (discord @ Ryoto Praeses#8312)
screen00300

characters included:
- ArbitraryRage
- Kenny
- Mallow
- Noelle
- Oskari
- Peeesh
- Peka
- Pellicius
- Riko
- Rya
- Ryo
- She
- Sora
- Spax
- Star (the blue dog)
- Star (the cat shark)
- Tari
- VoxelDev

### CODE REVIEW

**Comment by SpiritAxolotl** [comment]
this will be the first pull request to get one trillion forks

**Comment by Jecket22** [comment]
oh ym gdo

**Comment by Sudospective** [comment]
YES

RISE MY KAREN CHILDERN

**Comment by chlomakiii** [comment]
where the hell am i

**Pull request merged**
